names_for_cluster: ['movieId', 'genre_film-noir',
                    'genre_no genres listed', 'genre_drama',
                    'genre_mystery', 'genre_animation',
                    'genre_horror', 'genre_fantasy',
                    'genre_war', 'genre_crime', 'genre_comedy',
                    'genre_western', 'genre_adventure',
                    'genre_documentary', 'genre_imax',
                    'genre_action', 'genre_children',
                    'genre_musical', 'genre_thriller',
                    'genre_romance', 'genre_sci-fi']

names_interest_cum: ['time_day', 'movies', 'genre_crime',
                      'genre_no genres listed', 'genre_adventure',
                      'genre_romance', 'genre_horror', 'genre_drama',
                      'genre_thriller', 'genre_comedy', 'genre_imax',
                      'genre_documentary', 'genre_action', 'genre_musical',
                      'genre_sci-fi', 'genre_animation', 'genre_fantasy',
                      'genre_children', 'genre_western', 'genre_war',
                      'genre_mystery', 'genre_film-noir']

new_names_interest_cum: ['frecc_movies_per_day',
                          'frecc_genre_crime_per_day',
                          'frecc_genre_no genres listed_per_day',
                          'frecc_genre_adventure_per_day',
                          'frecc_genre_romance_per_day',
                          'frecc_genre_horror_per_day',
                          'frecc_genre_drama_per_day',
                          'frecc_genre_thriller_per_day',
                          'frecc_genre_comedy_per_day',
                          'frecc_genre_imax_per_day',
                          'frecc_genre_documentary_per_day',
                          'frecc_genre_action_per_day',
                          'frecc_genre_musical_per_day',
                          'frecc_genre_sci-fi_per_day',
                          'frecc_genre_animation_per_day',
                          'frecc_genre_fantasy_per_day',
                          'frecc_genre_children_per_day',
                          'frecc_genre_western_per_day',
                          'frecc_genre_war_per_day',
                          'frecc_genre_mystery_per_day',
                          'frecc_genre_film-noir_per_day']

cumulative_names: ['cumulativefrecc_genre_crime_per_day',
                     'cumulativefrecc_genre_no genres listed_per_day',
                     'cumulativefrecc_genre_adventure_per_day',
                     'cumulativefrecc_genre_romance_per_day',
                     'cumulativefrecc_genre_horror_per_day',
                     'cumulativefrecc_genre_drama_per_day',
                     'cumulativefrecc_genre_thriller_per_day',
                     'cumulativefrecc_genre_comedy_per_day',
                     'cumulativefrecc_genre_imax_per_day',
                     'cumulativefrecc_genre_documentary_per_day',
                     'cumulativefrecc_genre_action_per_day',
                     'cumulativefrecc_genre_musical_per_day',
                     'cumulativefrecc_genre_sci-fi_per_day',
                     'cumulativefrecc_genre_animation_per_day',
                     'cumulativefrecc_genre_fantasy_per_day',
                     'cumulativefrecc_genre_children_per_day',
                     'cumulativefrecc_genre_western_per_day',
                     'cumulativefrecc_genre_war_per_day',
                     'cumulativefrecc_genre_mystery_per_day',
                     'cumulativefrecc_genre_film-noir_per_day']

percen_cumulative_names: ['percencumulativefrecc_genre_crime_per_day',
                           'percencumulativefrecc_genre_no genres listed_per_day',
                           'percencumulativefrecc_genre_adventure_per_day',
                           'percencumulativefrecc_genre_romance_per_day',
                           'percencumulativefrecc_genre_horror_per_day',
                           'percencumulativefrecc_genre_drama_per_day',
                           'percencumulativefrecc_genre_thriller_per_day',
                           'percencumulativefrecc_genre_comedy_per_day',
                           'percencumulativefrecc_genre_imax_per_day',
                           'percencumulativefrecc_genre_documentary_per_day',
                           'percencumulativefrecc_genre_action_per_day',
                           'percencumulativefrecc_genre_musical_per_day',
                           'percencumulativefrecc_genre_sci-fi_per_day',
                           'percencumulativefrecc_genre_animation_per_day',
                           'percencumulativefrecc_genre_fantasy_per_day',
                           'percencumulativefrecc_genre_children_per_day',
                           'percencumulativefrecc_genre_western_per_day',
                           'percencumulativefrecc_genre_war_per_day',
                           'percencumulativefrecc_genre_mystery_per_day',
                           'percencumulativefrecc_genre_film-noir_per_day']
